version: '3.8'

# ============================================================================
# KaFlow-Py Docker Compose 开发配置
# 包含热重载和调试功能
# ============================================================================

services:
  kaflow-py-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: kaflow-py:dev
    container_name: kaflow-py-dev
    
    ports:
      - "8102:8102"
    
    environment:
      # 开发环境配置
      - KAFLOW_HOST=0.0.0.0
      - KAFLOW_PORT=8102
      - KAFLOW_RELOAD=true          # 启用热重载
      - KAFLOW_LOG_LEVEL=debug      # 调试日志级别
      
      # LLM API Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    
    volumes:
      # 挂载整个源代码目录，支持热重载
      - ../src:/app/src
      - ../server.py:/app/server.py
      - ../main.py:/app/main.py
      
      # 挂载日志目录
      - ./logs:/app/logs
      
      # 挂载数据目录
      - ./data:/app/data
    
    # 开发环境不自动重启
    restart: "no"
    
    networks:
      - kaflow-network

networks:
  kaflow-network:
    driver: bridge
    name: kaflow-network

