# =================================================================
# KaFlow-Py 浏览器自动化工具模版
# 使用 react_agent + browser_use tool 的方式实现浏览器自动化
# =================================================================

id: 2

# =================================================================
# 协议版本与元信息
# =================================================================
protocol:
  name: "浏览器自动化助手"
  version: "1.0.0"
  schema_version: "2025.09.10"
  description: "可以将用户的需求转换为浏览器自动化任务，并执行"
  author: "DevYK"
  license: "MIT"

# =================================================================
# 全局配置
# =================================================================
global_config:
  # 运行时配置
  runtime:
    timeout: 300
    max_retries: 3
    parallel_limit: 1
    debug_mode: false
    trace_enabled: true
    checkpoint_enabled: true

  # 日志配置
  logging:
    level: "INFO"
    format: "json"
    output: "stdout"
    file_path: "./logs/browser_tool.log"
    max_size: "50MB"
    max_files: 5

  # 内存配置
  # 记忆存储配置
  memory:                                    # 记忆存储配置 (可选)
    enabled: true                            # 启用记忆存储 (可选)
    provider: "memory"                       # 存储提供商: memory|redis|postgresql|mongodb|sqlite (可选)

# =================================================================
# Agent 配置
# =================================================================
agents:
  # 浏览器自动化 Agent
  browser_agent:
    name: "browser_agent"
    type: "react_agent"  # 使用 react_agent，支持工具调用
    description: "智能浏览器助手，可以使用浏览器自动化工具完成网页任务"
    enabled: true
    
    system_prompt: |
      你是一个智能浏览器助手，具备以下能力：
      
      1. 使用 browser_use 工具执行浏览器自动化任务
      2. 访问网站并提取信息
      3. 搜索和导航
      4. 数据抓取和分析
      
      工具使用说明：
      - browser_use: 执行浏览器自动化任务
        参数：task (要执行的任务描述)
        示例：browser_use(task="访问 github.com/browser-use/browser-use，获取项目的 star 数量")
      
      执行策略：
      1. 理解用户的需求
      2. 分析是否需要使用浏览器工具
      3. 如果需要，调用 browser_use 工具执行任务
      4. 解析工具返回的结果
      5. 给出清晰的回答
      
      注意事项：
      - 浏览器操作需要时间，请耐心等待
      - 如果任务失败，分析原因并尝试优化任务描述
      - 对于复杂任务，可以分步执行
    
    llm:
      provider: "openai"
      base_url: "https://api.ppinfra.com/v3/openai"
      api_key: "${DEEPSEEK_API_KEY}"
      model: "deepseek/deepseek-v3-0324"
      temperature: 0.3
      max_tokens: 4096
      timeout: 60
    
    # 工具配置 - browser_use
    tools:
      - name: "browser_use"
        type: "browser_use"  # 特殊标记，表示使用 browser_use tool
        description: "使用 AI 控制浏览器执行自动化任务"
        config:
          headless: false  # 是否无头模式
          disable_security: false
          window_w: 1280
          window_h: 1100
          save_recording_path: null
    
    mcp_servers: []

  # 总结 Agent
  summary_agent:
    name: "summary_agent"
    type: "agent"
    description: "对浏览器任务结果进行总结和分析"
    enabled: true
    
    system_prompt: |
      你是一个专业的数据分析和总结助手。你的任务是：
      1. 接收浏览器任务的执行结果
      2. 分析和整理收集到的信息
      3. 生成清晰、结构化的总结报告
      4. 提取关键信息和要点
      5. 如果有问题或异常，指出并给出建议
      
      总结时请：
      - 使用清晰的结构（标题、列表、段落）
      - 突出重要信息
      - 保持客观和准确
      - 如果数据不完整，明确说明
    
    llm:
      provider: "deepseek"
      base_url: "https://api.ppinfra.com/v3/openai"
      api_key: "${DEEPSEEK_API_KEY}"
      model: "deepseek/deepseek-v3-0324"
      temperature: 0.7
      max_tokens: 2048
      timeout: 30
    
    tools: []
    mcp_servers: []


# =================================================================
# 工作流配置
# =================================================================
workflow:
  name: "浏览器工具自动化工作流"
  version: "1.0.0"
  description: "使用 browser_use tool 执行浏览器任务，并对结果进行总结"
  author: "DevYK"
  schema_version: "2025.09.10"
  
  settings:
    timeout: 300
    max_retries: 3
    debug_mode: false

  # =================================================================
  # 节点定义
  # =================================================================
  nodes:
    # 开始节点
    - name: "start_node"
      type: "start"
      description: "工作流开始节点，接收用户的浏览器任务"
      position:
        x: 100
        y: 100
      outputs:
        - name: "user_query"
          type: "string"
          description: "用户的查询或任务描述"

    # 浏览器 Agent 节点
    - name: "browser_agent"
      type: "agent"
      description: "使用 browser_use tool 执行任务的智能 Agent"
      agent_ref: "browser_agent"
      position:
        x: 300
        y: 100
      
      inputs:
        - name: "query"
          type: "string"
          required: true
          source: "start_node.user_query"
          description: "用户查询"
      
      outputs:
        - name: "result"
          type: "string"
          description: "浏览器任务执行结果"
        - name: "status"
          type: "string"
          description: "执行状态"

    # 总结节点
    - name: "summary_agent"
      type: "agent"
      description: "总结浏览器任务结果"
      agent_ref: "summary_agent"
      position:
        x: 500
        y: 100
      
      inputs:
        - name: "browser_result"
          type: "string"
          required: true
          source: "browser_agent.result"
          description: "浏览器任务的原始结果"
        - name: "original_query"
          type: "string"
          required: true
          source: "start_node.user_query"
          description: "原始用户查询"
      
      outputs:
        - name: "summary"
          type: "string"
          description: "结构化的总结报告"

    # 结束节点
    - name: "end_node"
      type: "end"
      description: "工作流结束节点"
      position:
        x: 700
        y: 100
      inputs:
        - name: "final_summary"
          type: "string"
          required: true
          source: "summary_agent.summary"
          description: "最终总结报告"

  # =================================================================
  # 边定义
  # =================================================================
  edges:
    - from: "start_node"
      to: "browser_agent"
      description: "传递用户查询到浏览器 Agent"
      
    - from: "browser_agent"
      to: "summary_agent"
      description: "传递浏览器结果到总结 Agent"
      
    - from: "summary_agent"
      to: "end_node"
      description: "输出最终总结报告"
